#!/bin/bash
while true; do
sleep 5
clear

echo "
please select:

1. display system info
2. display disk space
3. display home space uili
0. quit
"

read -p "enter selection [0-3] > "

if [[ "$REPLY" =~ ^[0-3]$ ]]; then
	if [[ "$REPLY" == 0 ]]; then
		echo "program terminated"
		break
	fi
	if [[ "$REPLY" == 1 ]]; then
		echo "hostname: $HOSTNAME"
		uptime
#		sleep "$DELAY"
		continue
	fi
	if [[ "$REPLY" == 2 ]]; then
		df -h
#		sleep "$DELAY"
		continue
	fi	
	if [[ "$REPLY" == 3 ]]; then
		if [[ "$(id -u)" -eq 0 ]]; then
			echo "HOME SPACE UTIL (ALL USER)"
			du -sh /home/*
		else
			echo "home space util($USER)"
			du -sh "$HOME"

		fi
#		sleep "$DELAY"
		continue
	fi
else
	echo "invalid entry" >&2
#	sleep "$DELAY"
fi
done
